export const ADMIN_ROUTE = '/admin'
export const MAIN_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CATALOG_ROUTE = '/catalog'
export const CONTACTS_ROUTE = '/contacts'
export const DELIVERY_PAYMENT_ROUTE = '/delivery-payment'
export const REVIEWS_ROUTE = '/reviews'
export const CART_ROUTE = '/cart'
export const PRODUCT_ROUTE = '/product'
export const USER_PAGE_ROUTE = '/user'
export const ORDERS_ROUTE = ADMIN_ROUTE + '/orders';
export const PRODUCTS_CONTROL_ROUTE = ADMIN_ROUTE + '/products'
export const PRODUCT_EDIT_ROUTE = PRODUCTS_CONTROL_ROUTE + '/edit';